name: Global Narrative Analysis

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # آخرین نسخه

      - name: Python Setup
        uses: actions/setup-python@v5 # آخرین نسخه
        with:
          python-version: '3.10'

      - name: Install Libs
        run: |
          pip install feedparser openai pandas jinja2 python-dateutil

      - name: Run Engine
        env:
          LIARA_AI_API_KEY: ${{ secrets.LIARA_AI_API_KEY }}
        run: python analyzer.py

      - name: Save Data
        run: |
          git config --global user.name 'NarrativeBot'
          git config --global user.email 'bot@github.com'
          git add data/videos.json index.html
          git commit -m "Auto-update analysis" || echo "No changes"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3 # رفع خطای نسخه 3 شما
        with:
          path: '.'

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
